import { ApplicationConfig, importProvidersFrom } from '@angular/core';
import {
  provideHttpClient,
  withInterceptors
} from '@angular/common/http';
import { provideRouter } from '@angular/router';
import { provideAnimations } from '@angular/platform-browser/animations';

import { routes } from './app.routes';
import {
  LucideAngularModule,
  LogOut,
  Edit,
  Trash2,
  Eye,
  CircleUser,
  Search,
  FilePenLine,
  Trash2Icon,
  PlusCircle,
  CheckCircle,
  Info,
  ArrowLeft,
  Package,
  PackageX,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  LoaderCircle,
  RefreshCw,
  SearchX,
  ImageOff,
  ArrowRight,
  RotateCw,
  SlidersHorizontal,
  X,
  Star,
  Menu,
  User,
  ShoppingCart,
  Home,
  BarChart,
  BarChart2,
  ChartLine,
  Facebook,
  Twitter,
  Plus,
  Heart,
  LayoutDashboard,
  Minus,
  MessageCircle,
  UserPlus,
  UserPlusIcon,
  LogIn,
  // Dashboard Icons
  DollarSign,
  Users,
  TrendingUp,
  LineChart,
  Download,
  Loader,
} from 'lucide-angular';
import { authInterceptor } from './core/interceptors/auth.interceptor';

export const appConfig: ApplicationConfig = {
  providers: [
    provideRouter(routes),
    provideAnimations(),
    importProvidersFrom(
      LucideAngularModule.pick({
        LogOut,
        Edit,
        Trash2,
        Eye,
        CircleUser,
        Search,
        FilePenLine,
        Trash2Icon,
        PlusCircle,
        CheckCircle,
        Info,
        ArrowLeft,
        Package,
        PackageX,
        ChevronDown,
        ChevronLeft,
        ChevronRight,
        LoaderCircle,
        RefreshCw,
        SearchX,
        ImageOff,
        ArrowRight,
        SlidersHorizontal,
        RotateCw,
        Home,
        ShoppingCart,
        User,
        X,
        Star,
        Menu,
        BarChart,
        BarChart2,
        ChartLine,
        Facebook,
        Twitter,
        Plus,
        Heart,
        LayoutDashboard,
        Minus,
        MessageCircle,
        UserPlus,
        UserPlusIcon,
        LogIn,
        // Dashboard Icons
        DollarSign,
        Users,
        TrendingUp,
        LineChart,
        Download,
        Loader
      })
    ),
    provideHttpClient(withInterceptors([authInterceptor])),
  ],
};
